### ISSUE TITLE
Will your team release the dataset mentioned in the paper?

### ISSUE THREAD

**Issue by siyuada** [svip-lab/PPGNet#10]
Hey, I noticed that you mentioned a new dataset which include both indoor and outdoor images. It's a wonderful work, and could help other researcher begin their work. Will your team release the dataset mentioned in the paper?

**Comment by lee2430** [comment]
Hi @siyuada , thanks for your interest, the data is now available at [GoogleDrive](https://drive.google.com/open?id=13zmiuHL__fdTY5Z7_-k75H3VhBVyFquJ) or [BaiduPan](https://pan.baidu.com/s/1ilrkY1lOvup0qncLAUxdvA) (code: 2a9y).

**Comment by MiracleHW** [comment]
> Hi @siyuada , thanks for your interest, the data is now available at [GoogleDrive](https://drive.google.com/open?id=13zmiuHL__fdTY5Z7_-k75H3VhBVyFquJ) or [BaiduPan](https://pan.baidu.com/s/1ilrkY1lOvup0qncLAUxdvA) (code: 2a9y).

I use the 'pikcle.load()' or referring to the code in 'data/line_graph.py' use 'LineGraph().load()' to read the '.lg' annotation file  both raise the error 'Segmentation fault (core dumped)'.  How can I read the '.lg' file.

**Comment by siyuada** [comment]
@lee2430 WOW, really thanks your work and open source spirit!!

**Comment by JanineCHEN** [comment]
> > Hi @siyuada , thanks for your interest, the data is now available at [GoogleDrive](https://drive.google.com/open?id=13zmiuHL__fdTY5Z7_-k75H3VhBVyFquJ) or [BaiduPan](https://pan.baidu.com/s/1ilrkY1lOvup0qncLAUxdvA) (code: 2a9y).
> 
> I use the 'pikcle.load()' or referring to the code in 'data/line_graph.py' use 'LineGraph().load()' to read the '.lg' annotation file both raise the error 'Segmentation fault (core dumped)'. How can I read the '.lg' file.

Hi, same question here. It would be great if you could share some insight on how to read and interpret the .lg file. Also wondering how to create one using my own images. Thank you.
