### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by lunana123** [svip-lab/PPGNet#2]
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by allankevinrichie** [comment]
You probably didn't download the backbone checkpoint files correctly. These files were uploaded with git-lfs. If the files in your `./ckpt/backbone/` are less than 1MB, then you might only pull the links to them.

**Comment by rayryeng** [comment]
Install Git LFS first: https://help.github.com/en/articles/installing-git-large-file-storage

After, inside the directory of the repository, make sure you pull the backbone files:

`git lfs pull`

Each of the files should be around a couple hundred MB or so.
