### ISSUE TITLE
too many "find 0 jucntions" in the log message

### ISSUE THREAD

**Issue by magic428** [svip-lab/PPGNet#4]
`find 0 jucntions. find 0 jucntions. epoch: [1][1382/2500], lr: 0.2, time_total: 1.87, time_data: 0.01, time_net: 1.70, time_vis: 0.16, loss: 0.4219, loss_heatmap: 0.1099, loss_adj_mtx: 0.0624 find 0 jucntions. find 0 jucntions. epoch: [1][1383/2500], lr: 0.2, time_total: 1.87, time_data: 0.01, time_net: 1.70, time_vis: 0.16, loss: 0.4001, loss_heatmap: 0.1532, loss_adj_mtx: 0.0494 find 0 jucntions. find 0 jucntions. epoch: [1][1384/2500], lr: 0.2, time_total: 1.87, time_data: 0.01, time_net: 1.70, time_vis: 0.16, loss: 0.4026, loss_heatmap: 0.1498, loss_adj_mtx: 0.0506 find 0 jucntions. find 0 jucntions. epoch: [1][1385/2500], lr: 0.2, time_total: 1.87, time_data: 0.01, time_net: 1.70, time_vis: 0.16, loss: 0.4419, loss_heatmap: 0.1236, loss_adj_mtx: 0.0637 find 0 jucntions. find 0 jucntions. epoch: [1][1386/2500], lr: 0.2, time_total: 1.87, time_data: 0.01, time_net: 1.70, time_vis: 0.16, loss: 0.5633, loss_heatmap: 0.1879, loss_adj_mtx: 0.0751 find 0 jucntions. find 0 jucntions. epoch: [1][1387/2500], lr: 0.2, time_total: 1.87, time_data: 0.01, time_net: 1.70, time_vis: 0.16, loss: 0.3670, loss_heatmap: 0.1545, loss_adj_mtx: 0.0425 find 0 jucntions. find 0 jucntions. epoch: [1][1388/2500], lr: 0.2, time_total: 1.87, time_data: 0.01, time_net: 1.70, time_vis: 0.16, loss: 0.4504, loss_heatmap: 0.1039, loss_adj_mtx: 0.0693 find 0 jucntions. find 0 jucntions. epoch: [1][1389/2500], lr: 0.2, time_total: 1.87, time_data: 0.01, time_net: 1.70, time_vis: 0.16, loss: 0.4568, loss_heatmap: 0.0956, loss_adj_mtx: 0.0722 find 0 jucntions. find 0 jucntions. epoch: [1][1390/2500], lr: 0.2, time_total: 1.87, time_data: 0.01, time_net: 1.70, time_vis: 0.16, loss: 0.3710, loss_heatmap: 0.1334, loss_adj_mtx: 0.0475`

Is this training properly? or If not, what should I do?

**Comment by allankevinrichie** [comment]
If you saw this during the early stage of training, just do not worry. This is a normal behavior due to the fact that the junction heatmaps are basically zeros everywhere except for a few non-zero values. The network will try to output a black map to minimize the overall loss in the early stage.

**Comment by magic428** [comment]
Thanks for reply.

**Comment by JanineCHEN** [comment]
> If you saw this during the early stage of training, just do not worry. This is a normal behavior due to the fact that the junction heatmaps are basically zeros everywhere except for a few non-zero values. The network will try to output a black map to minimize the overall loss in the early stage.

Hi, if such being the case, how many epochs should be reasonable for getting non-zero junctions?? Thank you.

**Comment by readmees** [comment]
After 4 epochs on the rooftop dataset I already started seeing some jucntions
