### ISSUE TITLE
specify the dataset path in the train.sh script

### ISSUE THREAD

**Issue by glushakviktor** [svip-lab/PPGNet#5]
Step 3. specify the dataset path in the train.sh script.

For example, I extract the archive to the root of the project (<root>/indoorDist).

In train.sh:

python main.py \
--exp-name line_weighted_wo_focal_junc --backbone resnet50 \
--backbone-kwargs '{"encoder_weights": "ckpt/backbone/encoder_epoch_20.pth", "decoder_weights": "ckpt/backbone/decoder_epoch_20.pth"}' \
--dim-embedding 256 --junction-pooling-threshold 0.2 \
--junc-pooling-size 64 --attention-sigma 1.5 --block-inference-size 16 \
--data-root /data/path --junc-sigma 3 \
--batch-size 16 --gpus 0,1,2,3 --num-workers 10 --resume-epoch latest \
--is-train-junc True --is-train-adj True \
--vis-junc-th 0.1 --vis-line-th 0.1 \
    - train --end-epoch 9 --solver SGD --lr 0.2 --weight-decay 5e-4 --lambda-heatmap 1. --lambda-adj 5. \
    - train --end-epoch 15 --solver SGD --lr 0.02 --weight-decay 5e-4 --lambda-heatmap 1. --lambda-adj 10. \
    - train --end-epoch 30 --solver SGD --lr 0.002 --weight-decay 5e-4 --lambda-heatmap 1. --lambda-adj 10. \
    - end

Tell me please where I have to set path in this script?

**Comment by rayryeng** [comment]
Here: `--data-root /data/path`.  You need to download the data, extract it then modify this field to point to where the data is located.  If you extracted it correctly, it should be a directory called `indoorDist`.  Simply change the path to point to this directory.

**Comment by allankevinrichie** [comment]
Thanks, @rayryeng ! I'll add some notes about it in the README.md.
